apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 80
