apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
    tag: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - image: agimenezibanez/nameko-example-orders:dev
        imagePullPolicy: Always
        name: orders
        env:
          - name: DB_HOST
            value: db-postgresql
          - name: DB_NAME
            value: orders
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-postgresql
                key: postgresql-password
          - name: RABBIT_HOST
            value: broker-rabbitmq
          - name: RABBIT_MANAGEMENT_PORT
            value: "15672"
          - name: RABBIT_PORT
            value: "5672"
          - name: RABBIT_USER
            value: user
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: broker-rabbitmq
                key: rabbitmq-password
      restartPolicy: Always
